### ISSUE TITLE
Habéis reventado la identidad, Enhorabuena! 

### ISSUE THREAD

**Issue by flrnd** [WPGranada/Wordcamp-visual-identity#1]

**Comment by flrnd** [comment]
Se que nadie del año pasado va a dar un paso al frente para hacer una crítica constructiva, y que, en el fondo, yo debería hacer lo mismo. Pero, simplemente por el curro voluntario que desarrollamos el año pasado, me parece que se os ha ido la mano en cuestión de customización. 

Una identidad es algo que se desarrolla para perdurar en el tiempo. No ir cambiando colores a placer. Habéis jugado a nivel púramente estético y una identidad, son valores.

¿Dónde están los valores de diversidad y comunidad con esa nueva paleta cromática? ¿O la referencia a granada? 

La cuestión es, ¿os "gustaban" más una gama de azules? Es triste ver como un concepto que surgió tras bastantes horas de trabajo se tira por la borda simplemente por un cambio de gestión y malas tomas de decisiones.

**Comment by davidperezgar** [comment]
Buenas Raúl, 

No entiendo tu crítica, cuando la imagen tiene que ir evolucionando, este año hemos cambiado los colores y la propuesta nos ha gustado a todo el equipo.

Siento que te sientas así, pero tenemos que innovar. 

Saludos.

**Comment by flrnd** [comment]
> No entiendo tu crítica, cuando la imagen tiene que ir evolucionando, este año hemos cambiado los colores y la propuesta nos ha gustado a todo el equipo.

Eso no es Innovar, ¿o tu acaso ves a coca-cola cambiando los colores corporativos todos los años? La imágen no evoluciona, lo que evolucionan son los recursos. Pero claro, eso lo entiende alguien que verdaderamente entiende de brandig y no alguien que juega a profesional del sector :)

**Comment by davidperezgar** [comment]
Bueno Raúl, la diseñadora que lo ha realizado trabaja para Renfe, y otras grandes empresas. Yo trabajo en una Agencia. Algo de esto entendemos. Creo que deberías retirar lo de "no alguien que juega a profesional del sector". Las formas te pierden.

Fin del tema.

**Comment by flrnd** [comment]
>Algo de esto entendemos.

A ellas no las conozco, y no voy a opinar. Pero tu bien poco entiendes del tema. Si David, Fin del tema.

**Comment by davidperezgar** [comment]
No merece la pena que te conteste. Fin.

**Comment by jesusyesares** [comment]
Raúl, sabes que te aprecio como persona y como profesional.

Pero no puedo apoyar lo que has hecho. Sabes de sobra que somos voluntarios, que todo esto lo hacemos quitándonos el tiempo de nuestro trabajo, y lanzar la bomba que has lanzado me ha parecido gratuito.

Me parece que le debes una disculpa a las chicas y en especial a David, que está liderando esto con toda solvencia.

Partiendo de la base de que no tengo ni puta idea de diseño, no obstante lo estudié. El trabajo que han hecho las diseñadoras me parece excelente, me consta que han respetado en todo momento el trabajo original, y yo llevaré con orgullo la camiseta de esta WordCamp porque me encanta y porque representa otro año de trabajo en equipo hasta el último día, cuando toca barrer el local.

En fin, sé que en el fondo no lo haces con maldad, pero hoy se te ha ido del todo.

Un abrazo
